Bwt
Ivan-Pokhabov/Homework-2semester pull request #1
Opened 2024-02-21 19:28 UTC by Ivan-Pokhabov

2024-02-21 20:30 UTC, AlexPoziev commented
PR выглядит страшно :)

У вас, кажется, не перенеслись изменения из main, поэтому все так грустно (а вообще когда ГХ явно пишет, что у вас конфликт, то нужно насторожиться)

В случаях когда хотите добавить изменения из main, то можно воспользоваться `rebase` (на самом деле его можно использовать и когда хотите поменять ветку от которой отводитесь), но можно попробовать и пошаманить с `merge`, как минимум ознакомиться с обоими стоит. 
`rebase` возьмет текущее состояние main и положит ваши коммиты из пулл-реквеста на них (main не пострадает если все правильно сделать)

Когда исправите -- добавьте в ревьюеры.
На всякий случай это делается тут:

![Screenshot 2024-02-21 at 11 14 10 pm](https://github.com/Ivan-Pokhabov/Homework-2semester/assets/112957370/7830507a-cdcf-4412-8ee7-6979dd85a7af)

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +    return true;
Если не лень, то было бы славно, если вы написал бы тесты с использованием NUnit. Там можно будет записать все ваши тесты в один метод с использование `[TestCase]`

Но как минимум ознакомится с паттерном ARRANGE-ACT-ASSERT крайне советую, то есть код бы выглядел примерно так:

```suggestion
    const string testString = "abcd";
    const string expectedStringResult = "dabc";
    const int expectedIndexResult = 1;
    
    var (actualStringResult, actualIndexResult) = BWT(testData);
    
    return expectedStringResult == actualStringResult &&
         expectedIndexResult ==  actualIndexResult &&
         expectedStringResult == testString
```

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +    if (!String.Equals("dabc", BWTString) || originalStringIndex != 1 || !String.Equals(str, ReverseBWT(BWTString, originalStringIndex)))
У примитивного класса `string` оператор `==` идентичен `string.Equals(str1, str2)`

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +    Environment.Exit(-1);
Не нужно писать `Exit()`. Можно просто сообщить об ошибке и ее причине и сделать `return`

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +Console.WriteLine(ReverseBWT(BWTString, originalStringIndex));
Если все-таки консольное приложение, а не библиотека, то напишите юзеру, что выводится в консоль

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +﻿using System.Linq.Expressions;
Удалите, они не используются

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +            BWTString.Append(str[str.Length - 1]);
```suggestion
            BWTString.Append(str[^1]);
```

2024-02-22 20:37 UTC, AlexPoziev commented on BWT/Program.cs
> +    return true;
https://github.com/Ivan-Pokhabov/Homework-2semester/assets/112957370/ac4dbef1-6728-4f7e-8c6e-ba211942fdf6

2024-02-22 20:42 UTC, AlexPoziev commented on BWT/Program.cs
> +    Array.Sort(shifts, (int a, int b) => { if (str[a] < str[b]) return -1; if (str[a] > str[b]) return 1; return 0; });
Еще не нужно писать функции в одну строчку, читаемость сильно падает
```suggestion
    Array.Sort(shifts, (int a, int b) => 
    { 
        if (str[a] < str[b]) 
            return -1; 
        return str[a] < str[b] ? 1 : 0
    });
```

2024-02-22 20:49 UTC, Ivan-Pokhabov commented on BWT/Program.cs
> +    return true;
Это ужас, мне стыдно

2024-02-23 08:12 UTC, AlexPoziev commented on BWT/Program.cs
> +    return true;
Да ладно, ничего стыдного, бывает :)

2024-02-24 11:20 UTC, AlexPoziev commented on BWT/BWT.cs
> +            return string.Empty;
У вас появился отдельный публичный класс `BWT`, который, в теории, вы или кто-то другой захочет в дальнейшем использовать в других методах. И если они вызовут данный метод с неверными аргументами, то получат просто пустую строку, а о том что это "incorrect input" не узнают, так как вывод в консоль им ничего не дает. И тут сразу у вызывающего появляется вопрос: а пустая строка это ожидаемое поведение или нет? Человеку, которому нужно просто вызвать метод обратного преобразования(мб он даже алгоритма не знает) может показаться, что все ок, и пустая строка -- корректный результат работы алгоритма, хотя BWTString был "aabb".

В таких случаях нужно бросать исключения через `throw`

2024-02-24 18:32 UTC, AlexPoziev requested changes
Не заметил сразу. Когда пишется замечание, ожидается, что оно будет исправлено везде, а не только в месте коммента

2024-02-24 18:32 UTC, AlexPoziev commented on BWT/BWT.cs
> +        int originalStringIndex = 1;
```suggestion
        var originalStringIndex = 1;
```

Есть еще много не исправленных мест

2024-02-24 18:32 UTC, AlexPoziev commented on BWT/BWT.cs
> +    private static int[] SuffixArrayBuild(string str)
Сначала идут `public` методы, потом `private`

2024-02-25 14:56 UTC, AlexPoziev reviewed
Когда пишутся замечания, то ожидается, что либо они будут исправлены, либо приведен довод, почему данное место ошибкой не является

2024-02-25 14:56 UTC, AlexPoziev commented on BWT/BWT.cs
> +            return string.Empty;
С прошлого ревью не исправлено

```suggestion
            throw new ArgumentOutOfRangeException(paramName: nameof(originalStringIndex));
```

2024-02-25 14:56 UTC, AlexPoziev commented on BWT/BWT.cs
> +        return (BWTString.ToString(), originalStringIndex);
Поставьте [StyleCop](https://github.com/StyleCop/StyleCop)

```suggestion
        }
        
        return (BWTString.ToString(), originalStringIndex);
```

2024-02-25 14:56 UTC, AlexPoziev commented on BWT/Program.cs
> +}
Копипаст не исправлен

2024-02-25 14:56 UTC, AlexPoziev commented on BWT/BWT.cs
> +            for(var h = 0; h < str.Length; ++h)
```suggestion
            for (var h = 0; h < str.Length; ++h)
```

2024-02-27 16:52 UTC, AlexPoziev commented on BWT/BWT/Program.cs
> +    }
https://github.com/AlexPoziev/SPbUCSharpSecondTerm/blob/master/Homework1/BWT/BWT/BWT/Program.cs

2024-02-27 17:27 UTC, Ivan-Pokhabov commented on BWT/BWT/Program.cs
> +    }
Исправил). Прошу прощения слишком сильно вдохновился

2024-02-27 17:57 UTC, AlexPoziev approved these changes
Всё, в целом остались только незначительные ошибки, так что макс. балл ваш :)

2024-02-27 17:58 UTC, merged